#!/usr/bin/env bash
# install.sh — install the MX Master 4 desktop addon (daemon + overlay) for the
# current user. Idempotent: safe to re-run; only ever creates/overwrites the
# files it owns, never deletes user data, never enables a service.
#
# What it installs (all under your home, except the one sudo udev step):
#   * overlay binary      -> ~/.local/bin/mx4-radial   (built with cmake)
#   * daemon package      -> ~/.local/lib/mx4desktop/mx4d/   (copied source)
#   * daemon launcher     -> ~/.local/bin/mx4d   (system python, NO venv/pip)
#   * systemd user units  -> ~/.config/systemd/user/{mx4desktop,mx4-overlay}.service
#   * udev rule           -> /etc/udev/rules.d/70-mx-master-4.rules   (needs sudo)
#   * default config      -> ~/.config/mx4desktop/config.ini   (only if absent)
#
# It deliberately does NOT run `systemctl --user enable` — it prints the exact
# command instead, so a reboot is never surprised by an auto-started service.
set -euo pipefail

# --- locate the repo (this script lives in packaging/) ----------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"

OVERLAY_SRC="${REPO_DIR}/overlay"
OVERLAY_BUILD="${OVERLAY_SRC}/build"
DAEMON_SRC="${REPO_DIR}/daemon/mx4d"

BIN_DIR="${HOME}/.local/bin"
LIB_DIR="${HOME}/.local/lib/mx4desktop"
UNIT_DIR="${HOME}/.config/systemd/user"
CONFIG_DIR="${HOME}/.config/mx4desktop"
CONFIG_FILE="${CONFIG_DIR}/config.ini"
UDEV_RULE_SRC="${SCRIPT_DIR}/udev/70-mx-master-4.rules"
UDEV_RULE_DST="/etc/udev/rules.d/70-mx-master-4.rules"

PYTHON_BIN="${MX4_PYTHON:-$(command -v python3 || command -v python)}"

log()  { printf '  %s\n' "$*"; }
step() { printf '\n==> %s\n' "$*"; }

# --- preflight --------------------------------------------------------------
step "Preflight"
if [[ -z "${PYTHON_BIN}" ]]; then
    echo "error: no python3/python on PATH (set MX4_PYTHON=/path/to/python)" >&2
    exit 1
fi
log "python: ${PYTHON_BIN} ($(${PYTHON_BIN} --version 2>&1))"
for tool in cmake; do
    if ! command -v "${tool}" >/dev/null 2>&1; then
        echo "error: '${tool}' is required to build the overlay" >&2
        exit 1
    fi
done

mkdir -p "${BIN_DIR}" "${LIB_DIR}" "${UNIT_DIR}" "${CONFIG_DIR}"

# --- 1. build + install the overlay binary ----------------------------------
step "Building the radial overlay (cmake)"
GEN_ARGS=()
if command -v ninja >/dev/null 2>&1; then
    GEN_ARGS=(-G Ninja)
fi
cmake -S "${OVERLAY_SRC}" -B "${OVERLAY_BUILD}" "${GEN_ARGS[@]}"
cmake --build "${OVERLAY_BUILD}"

OVERLAY_BIN="${OVERLAY_BUILD}/mx4-radial"
if [[ ! -x "${OVERLAY_BIN}" ]]; then
    echo "error: overlay build did not produce ${OVERLAY_BIN}" >&2
    exit 1
fi
install -Dm755 "${OVERLAY_BIN}" "${BIN_DIR}/mx4-radial"
log "installed ${BIN_DIR}/mx4-radial"

# --- 2. install the daemon as a python package (NO venv, NO pip) -------------
step "Installing the daemon package"
# Replace the package tree atomically-ish: clear the old copy, copy fresh, so a
# renamed/removed module never lingers. We only ever touch our own LIB_DIR.
rm -rf "${LIB_DIR}/mx4d"
# Copy the source tree, excluding caches/test artifacts.
mkdir -p "${LIB_DIR}/mx4d"
( cd "${DAEMON_SRC}" && \
  find . -name '__pycache__' -prune -o -name '*.pyc' -prune -o -type f -print0 | \
  while IFS= read -r -d '' f; do
      install -Dm644 "${f}" "${LIB_DIR}/mx4d/${f}"
  done )
log "installed daemon package -> ${LIB_DIR}/mx4d"

# Launcher: runs the SYSTEM python with PYTHONPATH pointed at LIB_DIR so
# `python -m mx4d` resolves. No venv, no pip — matches the runtime constraint.
cat > "${BIN_DIR}/mx4d" <<EOF
#!/usr/bin/env bash
# mx4d launcher (generated by install.sh). Runs the daemon with the system
# python and no virtualenv: PYTHONPATH points at the installed package tree.
export PYTHONPATH="${LIB_DIR}\${PYTHONPATH:+:\$PYTHONPATH}"
exec "${PYTHON_BIN}" -m mx4d "\$@"
EOF
chmod 755 "${BIN_DIR}/mx4d"
log "installed ${BIN_DIR}/mx4d (system python: ${PYTHON_BIN})"

# --- 3. install systemd user units (correct ExecStart paths) ----------------
step "Installing systemd user units"
# The packaged units use %h/.local/bin/... which systemd expands to \$HOME, so
# they are already correct for a per-user ~/.local install. Copy verbatim.
install -Dm644 "${SCRIPT_DIR}/systemd/mx4desktop.service" "${UNIT_DIR}/mx4desktop.service"
install -Dm644 "${SCRIPT_DIR}/systemd/mx4-overlay.service" "${UNIT_DIR}/mx4-overlay.service"
log "installed ${UNIT_DIR}/mx4desktop.service"
log "installed ${UNIT_DIR}/mx4-overlay.service"
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user daemon-reload || true
fi

# --- 4. default config (only if none exists) --------------------------------
step "Default config"
if [[ -e "${CONFIG_FILE}" ]]; then
    log "keeping existing ${CONFIG_FILE} (not overwritten)"
else
    # Let the daemon write its own fully-populated defaults (auto-detects the
    # task manager for this DE). PYTHONPATH so it imports the installed package.
    PYTHONPATH="${LIB_DIR}${PYTHONPATH:+:$PYTHONPATH}" \
        "${PYTHON_BIN}" -c 'from mx4d.config import load_config; load_config()'
    log "wrote default ${CONFIG_FILE}"
fi
# Point the overlay command at the installed binary so the daemon's lazy launch
# finds it even if ~/.local/bin is not on the service PATH.
PYTHONPATH="${LIB_DIR}${PYTHONPATH:+:$PYTHONPATH}" "${PYTHON_BIN}" - "$CONFIG_FILE" "${BIN_DIR}/mx4-radial" <<'PYEOF'
import sys, configparser
path, overlay_bin = sys.argv[1], sys.argv[2]
p = configparser.ConfigParser()
p.read(path, encoding="utf-8")
if not p.has_section("overlay"):
    p.add_section("overlay")
# Only set if unset or still the bare default, so a user override is respected.
cur = p.get("overlay", "command", fallback="").strip()
if cur in ("", "mx4-radial"):
    p.set("overlay", "command", overlay_bin)
    with open(path, "w", encoding="utf-8") as fh:
        p.write(fh)
PYEOF
log "overlay command -> ${BIN_DIR}/mx4-radial"

# --- 5. udev rule (the one step that needs sudo) ----------------------------
step "udev rule (needs sudo)"
if [[ -f "${UDEV_RULE_DST}" ]] && cmp -s "${UDEV_RULE_SRC}" "${UDEV_RULE_DST}"; then
    log "udev rule already up to date at ${UDEV_RULE_DST}"
else
    log "installing ${UDEV_RULE_DST} (you may be prompted for your password)"
    sudo install -Dm644 "${UDEV_RULE_SRC}" "${UDEV_RULE_DST}"
    sudo udevadm control --reload || true
    sudo udevadm trigger --subsystem-match=hidraw || true
    log "udev rule installed + reloaded (re-plug the receiver if access is denied)"
fi

# --- done -------------------------------------------------------------------
cat <<EOF

==> Done. Installed for user '$(id -un)'.

To start NOW (this session only, nothing auto-enabled):
    systemctl --user start mx4desktop.service mx4-overlay.service
    # or run them ad hoc in a terminal:
    #   mx4d --verbose
    #   mx4-radial            # service mode (no --demo)

To ENABLE autostart on every login (opt-in — NOT done by this installer):
    systemctl --user enable --now mx4desktop.service mx4-overlay.service

Config:    ${CONFIG_FILE}
Uninstall: ${SCRIPT_DIR}/uninstall.sh

If ~/.local/bin is not on your PATH, add it:
    export PATH="\$HOME/.local/bin:\$PATH"
EOF
